# Generated by Django 6.0.5 on 2026-05-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportsession',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supportsession',
            name='vapi_conversation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
